// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczE6U4Jqbrqwnayq0aHsQIju7WtTCxZ4',
    appId: '1:464985438905:web:f196c77f0f28f673cfb968',
    messagingSenderId: '464985438905',
    projectId: 'task-master-b6378',
    authDomain: 'task-master-b6378.firebaseapp.com',
    storageBucket: 'task-master-b6378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKa5uyqIRt4Q4T5qBvyMtK90SOgHJyJA',
    appId: '1:464985438905:android:8d9bedbbd46dcf31cfb968',
    messagingSenderId: '464985438905',
    projectId: 'task-master-b6378',
    storageBucket: 'task-master-b6378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWzO_4Knen6MZt1G2i_SuhqvwURsGuPgw',
    appId: '1:464985438905:ios:4e0d0c4393cbf9f2cfb968',
    messagingSenderId: '464985438905',
    projectId: 'task-master-b6378',
    storageBucket: 'task-master-b6378.appspot.com',
    iosBundleId: 'com.example.taskMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWzO_4Knen6MZt1G2i_SuhqvwURsGuPgw',
    appId: '1:464985438905:ios:4e0d0c4393cbf9f2cfb968',
    messagingSenderId: '464985438905',
    projectId: 'task-master-b6378',
    storageBucket: 'task-master-b6378.appspot.com',
    iosBundleId: 'com.example.taskMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDczE6U4Jqbrqwnayq0aHsQIju7WtTCxZ4',
    appId: '1:464985438905:web:5c053367f4089cc9cfb968',
    messagingSenderId: '464985438905',
    projectId: 'task-master-b6378',
    authDomain: 'task-master-b6378.firebaseapp.com',
    storageBucket: 'task-master-b6378.appspot.com',
  );
}
